### ISSUE TITLE
Typo in the notebook

### ISSUE THREAD

**Issue by CoolTomatos** [stefanomattia/jupyter-notebooks#1]
https://github.com/stefanomattia/jupyter-notebooks/blob/bb8bb7f968a55bdd78b8d95d44aae242722dad3b/earth-observation/Mount%20Sinabung%20eruption%20as%20seen%20by%20Sentinel-5P.ipynb#L27

I guess it should be 

> Let's import __our__ libraries 

😁😆😁

**Comment by stefanomattia** [comment]
Thanks! I fixed it
